previewsExpireAfterDays: 3

services:
  - type: web
    name: toolpad-issue-2340
    env: node
    rootDir: ./
    buildCommand: yarn && yarn build
    startCommand: yarn start
    pullRequestPreviewsEnabled: true
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
