apiVersion: v1
kind: page
spec:
  id: aPVmgNv
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Text
          name: text
          props:
            variant: h6
